### ISSUE TITLE
ERIN ISSUE

### ISSUE THREAD

**Issue by erineand** [CasperGrey/ThemeOMeter#11]
OK so for those that are slightly OCD... using that slider to choose the score is really really frustrating becuase I need to choose an even number

is it possible to be able to type the number in and the slider will move to the number youve typed in

**Comment by ottos13** [comment]
Following on from this - could we reset scores back to the middle on the save button?

**Comment by CasperGrey** [comment]
Ive adjusted it to 0.1 per move which i believe makes it easier for yout o be whole numbers. alot easier while still allowing people to be quite specific with their scores.

Happy to see feedback
